title: Dynamid Research Team
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  We are a research team focused on dynamid software and distributed systems.
  We are part of the CITI Laboratory at INSA Lyon, France.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: dynamid
twitter_username: citi_lab
rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - publications.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
